const ROOT = 'CURRENCY';

export const FETCH_RATES_REQUEST = `${ROOT}/FETCH_RATES_REQUEST`;
export const FETCH_RATES_SUCCESS = `${ROOT}/FETCH_RATES_SUCCESS`;
export const FETCH_RATES_FAILURE = `${ROOT}/FETCH_RATES_FAILURE`;

export const UPDATE_RATE_REQUEST = `${ROOT}/UPDATE_RATE_REQUEST`;
export const UPDATE_RATE_SUCCESS = `${ROOT}/UPDATE_RATE_SUCCESS`;
export const UPDATE_RATE_FAILURE = `${ROOT}/UPDATE_RATE_FAILURE`;

export const ADD_CURRENCY = `${ROOT}/ADD_CURRENCY`;
export const REMOVE_CURRENCY = `${ROOT}/REMOVE_CURRENCY`;

export const TOGGLE_ADD_CURRENCY_MODAL = `${ROOT}/TOGGLE_ADD_CURRENCY_MODAL`;
